# Generated by Django 4.2.8 on 2023-12-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='level',
            field=models.CharField(default='user', max_length=32),
        ),
    ]
