# Generated by Django 4.2.8 on 2024-01-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_prettynum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('pwd', models.CharField(max_length=16)),
            ],
        ),
    ]
