# Generated by Django 4.2.8 on 2024-01-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='pwd',
            field=models.CharField(max_length=64),
        ),
    ]
