# Generated by Django 4.2.8 on 2024-01-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('img', models.CharField(max_length=128)),
            ],
        ),
    ]
