# Generated by Django 4.2.8 on 2024-01-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0008_boss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='img',
        ),
        migrations.AddField(
            model_name='boss',
            name='avatar',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to='avatar/'),
        ),
    ]
